### ISSUE TITLE
ProfileService.GetProfileStore()

### ISSUE THREAD

**Issue by AscendedWise** [MadStudioRoblox/ProfileService#12]
Hello, I was trying to create a scope for my profile storage as my game will have multiple save files, and the same error.
`ServerScriptService.Core_Scripts.dataManager.profileService:1731: [ProfileService]: profile_store_name must be a string` is generated within the console each time. my code is displayed as shown
```
mainKey = "Test Place: 12"
playerSaveFile = "File: 1"
local GameProfileStore = ProfileService.GetProfileStore(
	{Name = mainKey, Scope = playerSaveFile},
	SETTINGS.ProfileTemplate
)
```
![image](https://user-images.githubusercontent.com/84874243/119719991-70360800-be37-11eb-91e2-b09af2736f2d.png)

I'm not sure if this is due to the profile service not supporting scope I'm sure I read that it did, or if my code was set up wrong, any feedback on this issue would be greatly appreciated.

**Comment by AshtonCMiller** [comment]
I suggest updating your Profile Service to the latest version and see if it works then. If it still doesn't, attach the new error given here as I am unable to trace the error given.

**Comment by AscendedWise** [comment]
> I suggest updating your Profile Service to the latest version and see if it works then. If it still doesn't, attach the new error given here as I am unable to trace the error given.

I see, my mistake it appears I had an older version, of the module. Thank you for your assistance.
