### ISSUE TITLE
SS of some errors logged using Discord webhook

### ISSUE THREAD

**Issue by Shariiii** [MadStudioRoblox/ProfileService#14]
Most common report from issue signal is this one:
"502: API Services rejected request with error. HTTP 500 (Internal Server Error)"
i get tons of ^ daily

Can you please check them and see if there is something that can possibly cause any kind of data loss or something bad ty

![Screenshot_35](https://user-images.githubusercontent.com/78413543/122450352-5748ee80-cfc0-11eb-9388-43da5217d1f2.png)
![Screenshot_38](https://user-images.githubusercontent.com/78413543/122450354-587a1b80-cfc0-11eb-8a1a-71c4c6bdd54e.png)
![Screenshot_36](https://user-images.githubusercontent.com/78413543/122450356-5a43df00-cfc0-11eb-88a9-7bb25c616edd.png)
![Screenshot_39](https://user-images.githubusercontent.com/78413543/122450360-5b750c00-cfc0-11eb-8d6a-0f62b67ab4de.png)
![Screenshot_37](https://user-images.githubusercontent.com/78413543/122450365-5ca63900-cfc0-11eb-8293-478bf591b13a.png)

**Comment by angrybino** [comment]
You should at least know what these errors even mean before making a stupid issue. It clearly states that it is a "internal server "error, not a issue with ProfileService.
