### ISSUE TITLE
Attempt to index nil with Release

### ISSUE THREAD

**Issue by atomicra1n** [MadStudioRoblox/ProfileService#22]
Hey, I know this is my third issue and I apologize for that, really but I have another problem.
I get the error attempt to index nil with release for some reason, sometimes, any idea why?

```function FunctionTable.GetOfflineProfile(UserId)
	local ProfileKey = "Player_"..UserId
	local profile = ProfileStore:LoadProfileAsync(ProfileKey, "ForceLoad")
	profile:Release()
	return profile
end

**Comment by lucasmz-dev** [comment]
You need to check that the profile is returned or not, if it's not, then it wasn't able to load properly.

**Comment by atomicra1n** [comment]
> You need to check that the profile is returned or not, if it's not, then it wasn't able to load properly.

How can I check that?

**Comment by lucasmz-dev** [comment]
@MegamiShin 
```lua
if profile == nil then
```
