### ISSUE TITLE
Ability to check a profile's size

### ISSUE THREAD

**Issue by l3dotdev** [MadStudioRoblox/ProfileService#24]
This is more of just a convenience but it would be nice to see a method that gives the ability to check how many characters/space `Profile.Data` and `Profile.MetaData.MetaTags` takes up in the datastore so that we can check whether the data needs to overflow to another profile. This can be done by combining `Profile.Data` and `Profile.MetaData.MetaTags` ourselves and encoding it to JSON to get the character count and compare that to the max character count a DataStoreKey can hold, however a built-in method would be nice.

**Comment by atomicra1n** [comment]
I personally would not use this but it most certainly could come in handy. +1

**Comment by LM-loleris** [comment]
I do not consider this feature being in the realm of ProfileService concerns, mostly because data size evaluation can be done perfectly externally without altering current ProfileService behaviour.
