### ISSUE TITLE
ProfileSerivce Error

### ISSUE THREAD

**Issue by Shariiii** [MadStudioRoblox/ProfileService#28]
Found this error on google analytics and it was recorded only once since I implemented the google analytics + ProfileSerivce into the game so just wanted to report it in case it is something important

`Script timeout: exhausted allowed execution time | ServerScriptService.SaveSystemProMax.ProfileService, line 2327`

**Comment by LM-loleris** [comment]
It's a known error, though by design it poses no threat to player data, especially at this rate.

Thank you for your input!
