### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by moez-salahuddin** [MadStudioRoblox/ProfileService#30]
Could we please get a signal instance which fires whenever data within a Player's profile is changed? It would be a lifesaver for like UI which represents cash, it can easily be updated when the player's data is changed.

**Comment by Baileyeatspizza** [comment]
Alternatively, you could listen or check yourself when a Player's cash changes

for example
```lua
cash += 1
cashchanged()
```

I'm only suggesting that you handle this yourself as this will be hard to implement and go against overall performance. A slight modification of any key would result in that signal being fired.

**Comment by LM-loleris** [comment]
This project has no plans for data change signals.
Thank you for your input.
