### ISSUE TITLE
ProfileStore Not Adding to Data

### ISSUE THREAD

**Issue by Fideun** [MadStudioRoblox/ProfileService#44]
I looked everywhere and i cant find any solutions also asked many poeple. Using ProfileDataHandler:Init() Doesnt Work just causes it to never load. I have to change the profiles stores whole name just for it to work which resets Everything.
![image](https://github.com/MadStudioRoblox/ProfileService/assets/172080462/26907638-93d7-42b2-9419-e4d2a1d7ee26)

**Comment by TheFastest10001** [comment]
I don't even see an Init function in your code?? And besides, you don't even need an Init function since when you require the module script, it will connect the PlayerAdded and PlayerRemoving events that you wrote in your code.
